cask "iterm2"
brew "git"
brew "git-secrets"
brew "zsh"
brew "tmux"
brew "vim"
cask "atom"
cask "visual-studio-code"
brew "go"
brew "python3"
brew "python@2"
brew "rbenv"
brew "protobuf"

# k8s
brew "kubernetes-cli"
tap "superbrothers/zsh-kubectl-prompt"
brew "zsh-kubectl-prompt"
brew "kubectx"
brew "stern"
tap "blendle/blendle"
brew "kns"

# aws
brew "aws-iam-authenticator"
cask "aws-vault"
brew "awscli"
brew "chamber"

# java
cask "adoptopenjdk"

# commands
brew "watch"

# linters
brew "hadolint"
brew "yamllint"

# tools
brew "jq"
brew "circleci"
