cask "iterm2"
brew "zsh"
brew "tmux"
brew "vim"
cask "atom"

# langs
brew "python3"
brew "rbenv"

# k8s
brew "kubernetes-cli"
tap "superbrothers/zsh-kubectl-prompt"
brew "zsh-kubectl-prompt"
brew "kubectx"
brew "stern"
tap "blendle/blendle"
brew "kns"

# aws
brew "aws-iam-authenticator"
cask "aws-vault"
brew "awscli"
brew "chamber"

# java
cask "adoptopenjdk"

# commands
brew "watch"

# linters
brew "hadolint"
brew "yamllint"

# tools
brew "jq"
brew "circleci"
